SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE role_member;
TRUNCATE TABLE role_members;

ALTER SEQUENCE role_member_sequence RESTART WITH 1;
ALTER SEQUENCE role_members_sequence RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;